### PR TITLE
add find method

### PR DESCRIPTION
**Pull request by LegitTalon**
This adds `cities.find()` which can be used like `cities.find({state_abbr: 'CO'})` which will give you an array of cities in Colorado. If the array has only one item in it, it just returns that item.

### CODE REVIEW

**Comment by sjlu** [comment]
Is it possible to submit a change without formatting? Looks like your editor really mangled it up.

**Comment by LegitTalon** [comment]
@sjlu I can rebase if you'd like

**Comment by LegitTalon** [comment]
@sjlu I fixed the pertinent formatting. I can add back in the EOL whitespace if you want but my editor makes that especially difficult.

**Comment by sjlu** [comment]
Hey @LegitTalon,

I refactored the library, let me know if what I've provided works for you. I'll close this pull request for now.

**Pull request closed without merging**
