### PR TITLE
use lodash's find and filter

### PR DESCRIPTION
**Pull request by LegitTalon**
Lodash's find and filter methods have all sorts of nifty features like passing in an object with multiple properties or a function to define your own find and filter logic.

### CODE REVIEW

**Comment by sjlu** [comment]
Interesting. I'm also kind of curious about the performance of `_.filter`. I'll sleep on it and (probably) merge it in.

**Comment by LegitTalon** [comment]
Unfortunately https://lodash.com/benchmarks is down right now. But lodash is super fast.

**Comment by niftylettuce** [comment]
:+1:

**Comment by sjlu** [comment]
Merged.

**Comment by LegitTalon** [comment]
thank you!

**Pull request merged**
